services:
  couchdb:
    image: couchdb:3
    environment:
      - SERVICE_FQDN_COUCHDB
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    healthcheck:
      test:
        - CMD
        - bash
        - '-c'
        - 'curl -sf -u $${COUCHDB_USER}:$${COUCHDB_PASSWORD} http://localhost:5984/'
      interval: 15s
      timeout: 15s
      retries: 5
      start_period: 30s
    volumes:
      - couchdb-data:/opt/couchdb/data
      - ./local.ini:/opt/couchdb/etc/local.d/local.ini
    restart: unless-stopped

volumes:
  couchdb-data: